# Build: docker build -t yax-frontend:latest -f Dockerfile_web .
# Run: docker run -it --rm -p 4200:4200 --name yax-frontend yax-frontend:latest

### STAGE 1: Build ###
# To speed up RUN ngcc after npm install
FROM node:14.18-alpine as builder
WORKDIR /app
COPY ./src/package.json ./
RUN mkdir -p /app
COPY ./src /app
RUN npm install
RUN npm run build --prod
#CMD ["npm", "start"]

### STAGE 2: Run with nginx ###
FROM nginx:stable-alpine
COPY ./config/nginx/etc/conf.d/default.conf /etc/nginx/conf/default.conf 
COPY --from=builder /app/dist/src /usr/share/nginx/html